version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./postgres/tmp/db:/var/lib/postgresql/data
    # Set environment variables on .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  web:
    build: rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - ./rails:/myapp
    ports:
      - "3001:3001"
    depends_on:
      - db
